[project]
name = "chru"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai",
    "tqdm",
    "xlrd",
    "dateparser",
    "pandas",
    "requests",
    "openpyxl",
    "scipy",
    "seaborn",
    "scikit-learn",
    "statsmodels",
    "krippendorff",
    "matplotlib",
    "ipykernel",
    "striprtf",
]
